pipeline {
    agent any

    stages {
        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("./kube-news:V${env.BUILD_ID}", '-f ./Dockerfile .')
                }
            }
        }
    }
}